default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: postgres
  password: postgres

development:
  <<: *default
  database: nexoos_app_development

test:
  <<: *default
  database: nexoos_app_test

production:
  <<: *default
  database: nexoos_app_production
  username: nexoos_app
  password: <%= ENV['NEXOOS_APP_DATABASE_PASSWORD'] %>
